prescription and dispensation using Drug
esaude/openmrs-module-pharmacyapi pull request #19
Opened 2017-06-01 10:11 UTC by Guimino

Creates Prescription and Dispensation using drug.
Created a mapping based on Regimen(concept) and DrugItem( which is one-to-one with drug) to define ARV drug Regimes.  created services and resouces to be used on POC

Removed All StockManagement Entities,

2017-06-01 10:23 UTC, valvijo requested changes

2017-06-01 10:23 UTC, valvijo commented on api/src/main/java/org/openmrs/module/pharmacyapi/api/model/SupplierService.java
> +
We don't need this class

2017-06-01 10:23 UTC, valvijo commented on api/src/main/java/org/openmrs/module/pharmacyapi/api/model/SupplierServiceImpl.java
> +
We don't need this

2017-06-01 10:23 UTC, valvijo commented on api/src/main/java/org/openmrs/module/pharmacyapi/api/model/stock/Lot.java
> -
We don't need this

2017-06-01 10:23 UTC, valvijo commented on api/src/main/java/org/openmrs/module/pharmacyapi/api/model/stock/StockEntry.java
> -
We don't need this

2017-06-01 10:23 UTC, valvijo commented on api/src/main/java/org/openmrs/module/pharmacyapi/api/model/stock/Supplier.java
> -
We don't need this

2017-06-01 13:55 UTC, valvijo approved these changes

2017-06-21 14:13 UTC, larslemos commented
Old PR, that was fixed and Merged on PR #20

2017-06-21 14:13 UTC, Guimino commented
this PR was moved To PR #20

2017-06-21 14:13 UTC, closed without merging